### ISSUE TITLE
Dúvida?

### ISSUE THREAD

**Issue by Marcos-Development-web** [lucyanovidio/portifolio#2]
Olá tudo bem, bom estava admirando seu portfólio, primeiramente queria dizer que está lindo, e uma dúvida se puder ajudar é em relação a como fazer esse efeito no menu quando da scroll e ele fica fixo e quando abre no mobile como se chama o efeito no background q deixa ele fosco

**Comment by lucyanovidio** [comment]
Oi, Marcos! Estou vendo que estava com dúvida e já fechou a issue. Talvez já tenha solucionado, mas eu apliquei o efeito Glassmorphism para embassar o fundo do elemento, tanto no nav, quanto no menu para o mobile. Apliquei:

`background: rgba(0, 0, 0, 0.7);`
`backdrop-filter: blur(1rem);`


Fundo preto com alpha (opacidade) em 0.7 e a prop de blur que embassa o fundo em 1rem.
Espero poder ter ajudado! Qualquer coisa, me chama no linkedin.  E obrigado pelo elogio! 🙏🏾
